version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - g++ --version
      - make requirements
      - make package
      - python -m pip install -e .
sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt
