name: Build and test

on: [push, pull_request]

jobs:
  build_test:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-latest"]
        python: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        make requirements
    - name: Static analysis
      if: "matrix.python == '3.8'"
      run: |
        make check
    - name: Build packages
      run: |
        make package
    - name: Repair wheels
      if: "matrix.os == 'ubuntu-20.04'"
      run: |
        pip install -U auditwheel patchelf
        auditwheel repair --plat manylinux_2_31_x86_64 --wheel-dir dist dist/what_url-*linux*.whl
    - name: Run tests
      run: |
        pip install -e .
        make coverage
    - name: Build docs with sphinx
      if: "matrix.python == '3.8' && matrix.os == 'ubuntu-20.04'"
      run: |
        make docs
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: what-url-packages
        path: dist/*
