version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "monthly"
